### PR TITLE
beta rc

### PR DESCRIPTION
**Pull request by Connoropolous**
Here is the changelog item for the main diff
https://github.com/holochain/holochain/blob/main/CHANGELOG.md#holochain_integrity_types-010-beta-rc1

### CODE REVIEW

**Comment by pospi** [comment]
Looks sensible to me, and can only presume it compiles for you. Thanks for starting on this! Curious why we need to inline such a lot of Nix config now though

**Comment by Connoropolous** [comment]
I am just basing off of what everyone seems to be doing... I took this overall nix config from the @holochain/client js package repository. I believe it's for the reason of `niv` which is an easy updating system.

**Comment by pospi** [comment]
fair enough! Hopefully it will go away again eventually like it has in the past ;p

**Comment by pospi** [comment]
FYI I tagged this at 0.1.1 for when we get to updating hREA

**Pull request merged**
